services:

  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    container_name: ccadb_monitor
    ports:
      - "8080:80"
    environment:
      LOG_STACK: "slack"
      LOG_LEVEL: "debug"
      LOG_SLACK_WEBHOOK_URL: ""
      LOG_TEAMS_WEBHOOK_URL: ""
      CA_OWNER: ""

